### ISSUE TITLE
Cannot change Wordpress site language

### ISSUE THREAD

**Issue by pkanel80** [MissVeronica/UM-Backend-Local-Language#1]
By enabling this plugin, the language site It's always set in English and you cannot change it .

**Comment by MissVeronica** [comment]
The plugin is using the browser setting for language. Try to change your browser language.

**Comment by pkanel80** [comment]
Can I modify it to working like this only for back-end?
BR/Panos

**Comment by MissVeronica** [comment]
Try to change line 18 to be true.
`define( 'UM_BROWSER_LANGUAGE_BACKEND', true );      // UM Backend use of the browser language`

**Comment by pkanel80** [comment]
tnx for feedback. you mean false? it's already true.

**Comment by MissVeronica** [comment]
I have made some changes now to version 2.1.0
Replace with the new code and test without any changes in the code.

**Comment by pkanel80** [comment]
thanks, looks ok now!!
